### PR TITLE
Add support for Bluetooth extended advertisements

### PR DESCRIPTION
**Pull request by gunnarbeutner**
**Add support for Bluetooth extended advertisements**

This allows us to restrict advertisements to a specific channel, i.e. 37 in this case. This channel has the lowest frequency and is therefore usually less affected by path attenuation.

Also, because nodes were previously advertising on two or more channels the RSSI/distance filter was seeing a lot more jitter because each Bluetooth channel has different radio characteristics  and usually somewhat different received signal strengths.

Unfortunately this doesn't solve this problem for non-ESPresense devices, but it's a first step.

channels-cmp

**Add PlatformIO environment for Seeed Studio XIAO ESP32C3**

Without the custom flash mode setting the devices weren't able to write to the filesystem.

### CODE REVIEW

**Comment by DTTerastar** [comment]
Updating my nodes right now to test this!

**Comment by gunnarbeutner** [comment]
Cool, make sure to grab the latest commit - I had to force-push the branch a couple of times due to silly bugs.

Also, I've tried to figure out how to get the current channel but I don't think the CPU is aware of that at any point in time. I can't seem to find any code for it (neither in the "firmware" nor in the ROM) - maybe I haven't looked hard enough but I've given up for now. I guess it's back to crude filtering.

**Comment by gunnarbeutner** [comment]
Oh, also, the min/max interval is garbage. Oops.

**Comment by DTTerastar** [comment]
Ths vastly Improves the variance in my testing.  I don't have any good data yet, but I also feel like it's making optimization work better.

**Review by DTTerastar — APPROVED** [review]

**Comment by gunnarbeutner** [comment]
Apparently if I don't call setLegacyAdvertisement(true) I get RSSI values that fluctuate in a 10 dBm band. Plus nodes without Bluetooth 5 obviously can't parse those advertisements. The call is unconditional now.

Should be good now I think.

**Comment by DTTerastar** [comment]
> Apparently if I don't call setLegacyAdvertisement(true) I get RSSI values that fluctuate in a 10 dBm band. Plus nodes without Bluetooth 5 obviously can't parse those advertisements. The call is unconditional now.
> 
> Should be good now I think.

Yeah I think we just want legacy advertisments, just the extended for it's channel capabilities.  Check out companion [0.5.2](https://github.com/ESPresense/ESPresense-companion/releases/tag/v0.5.2) you can see the variance while hovered over a device.

**Comment by DTTerastar** [comment]
2d47e45 Is significantly worse for me. I'm seeing lots of values on the calibration screen time out. Not sure yet, but we seem to have upset the amount of time spent listening to advertisements. it's very hard to balance the radio time on these devices.

**Comment by DTTerastar** [comment]
I'm running the beta again, and I'm coming to be fond of the variance with all channels it does seem to show whether where you placed the nodes is a good spot or not. I believe the higher values are because of the higher power the nodes transmit at (stronger signal can also get much weaker with multi path obstructions, etc, thus higher variance).

**Comment by gunnarbeutner** [comment]
Hm yeah, this patch doesn't really solve the problem for non-ESPresense devices anyway.

**Comment by gunnarbeutner** [comment]
Feel free to give this a shot: https://github.com/ESPresense/ESPresense/tree/channel-info

There are still quite a few TODOs though. Right now it doesn't handle devices which only advertise on one or two channels gracefully (i.e. the weighted average is messed up because the channels' distance is 0).

One thing (unrelated to the channel patch) I've noticed while testing is that the variance is affected by outliers quite a lot and doesn't always reflect how "bad" the raw values change. Also it's affected by the sample rate: If you're missing advertisement packets for some reason the variance can get stuck until after you've received at least 12 packets.

For example in "var37":

Screenshot 2023-12-06 at 14 12 06

**Pull request closed without merging**
