### PR TITLE
Update platformio.ini

### PR DESCRIPTION
**Pull request by chrismcneil**
Fix for https://github.com/ESPresense/ESPresense/issues/900

## Summary by CodeRabbit

- **New Features**
  - Improved flash mode configuration for the `esp32c3` board, enhancing performance and reliability during firmware uploads.

### CODE REVIEW

**Comment by chrismcneil** [comment]
Is anything else missing for this PR to be successful?

**Comment by jaburges** [comment]
HI folks, Can we get this approved please? Just bricked a device as for some reason when I flashed an ESP32C3 with ESPresense I wasnt able to save any of the settings (including WiFi) 

[SIDE NOTE - What way is there to recover the device if OTA is the only option, and none of the details can be saved from the settings?)

**Comment by chrismcneil** [comment]
> HI folks, Can we get this approved please? Just bricked a device as for some reason when I flashed an ESP32C3 with ESPresense I wasnt able to save any of the settings (including WiFi) 
> 
> 
> 
> [SIDE NOTE - What way is there to recover the device if OTA is the only option, and none of the details can be saved from the settings?)

I ended up having to open mine and flashed tasmota thinking I could then ota the new build but sadly partitions are not compatible so I will have to solder it yet again.

**Comment by jaburges** [comment]
> > HI folks, Can we get this approved please? Just bricked a device as for some reason when I flashed an ESP32C3 with ESPresense I wasnt able to save any of the settings (including WiFi)
> > [SIDE NOTE - What way is there to recover the device if OTA is the only option, and none of the details can be saved from the settings?)
> 
> I ended up having to open mine and flashed tasmota thinking I could then ota the new build but sadly partitions are not compatible so I will have to solder it yet again.

Super weird, I had a bunch of partition issues, but I wondered if I did something wrong.
So I compiled firmware with your change `board_build.flash_mode = dio` via VSCode. Then flashed that firmware.bin to the device and it worked.

**Pull request merged**
