### PR TITLE
Turn off deprecated send to rooms (you can still enable it again until v4)

### PR DESCRIPTION
**Pull request by DTTerastar**
*breaking*

### CODE REVIEW

**Comment by N3rdix** [comment]
@DTTerastar does this mean https://www.home-assistant.io/integrations/mqtt_room/ needs to be adjusted as well as it works on the rooms topic?
I'm wondering how to preserve those sensors working after v4.

**Comment by DTTerastar** [comment]
Yeah specifying devices is also more efficient since it doesn't need to troll through lots of irrelevant messages.

**Comment by fisch55** [comment]
Hi @all.
got a Problem after Updating to 3.3.1.

just make the new format in HA like this.
In ESP ist shows me, my devices correctly....

But in HA it shows the device as unknown....

` platform: mqtt_room
    device_id: "irk:1b0xxxxxxxxxxx34"
    name: ESP AppleWatch Tom
    unique_id: 'ESP AppleWatch Tom'
    state_topic: "espresense/devices/irk:1b0xxxxxxxxxxx34"
    timeout: 10
    away_timeout: 120`


Thx for helping me...

**Comment by fisch55** [comment]
Hi
got a Problem after Updating to 3.3.1.

just make the new format in HA like this.
In ESP ist shows me, my devices correctly....

But in HA it shows the device as unknown....

platform: mqtt_room
device_id: "irk:1b0xxxxxxxxxxx34"
name: Iphone Tom
unique_id: 'Iphone Tom'
state_topic: "espresense/devices/irk:1b0xxxxxxxxxxx34"
timeout: 10
away_timeout: 120

Did I something wrong?
Thx for helping me...

**Comment by rwjack** [comment]
3.3.1 broke my setup. 

I changed from:

```
- platform: mqtt_room
  name: "Beacon1"
  device_id: "iBeacon:AAAAAAAA-1212-B2B3-6E2E-ABCABC000001-3838-5151" # [Redacted]
  state_topic: "espresense/rooms"
  away_timeout: 30
```

To:

```
- platform: mqtt_room
  name: "Beacon1"
  device_id: "iBeacon:AAAAAAAA-1212-B2B3-6E2E-ABCABC000001-3838-5151"
  state_topic: "espresense/devices/iBeacon:AAAAAAAA-1212-B2B3-6E2E-ABCABC000001-3838-5151"
  away_timeout: 30
```

And the sensor is not being updated in HA, even though I see the iBeacon on my node `espresense/ui/#/fingerprints`

Enabling send to rooms and switching back, works though.

**Comment by DTTerastar** [comment]
I think it's the casing.  AAAAAAAA-1212-B2B3-6E2E-ABCABC000001-3838-5151 should be lowercase.

**Comment by rwjack** [comment]
@DTTerastar Nope, wasn't it. The espresense node sees the beacon in fingerprints (include filter is working), although the HA mqtt_room integration won't update the sensors. Do you think this issue belongs there somewhere?

**Comment by rwjack** [comment]
Yep, that was the issue, thanks!

**Comment by jar87** [comment]
Hello. Anyone could help? Since last HA update to version 2023.11 and after updating espresense to 3.3.1 my espresense sensor isn`t working. It`s showing all time not_home and distance: null

In configuration.yaml i`ve changed code from:

```
  - platform: mqtt_room
    name: "Mi watch BLE"
    device_id: "iBeacon:e59ed151-4d13-4328-b777-f92449088eb0_100_1"
    state_topic: "espresense/rooms"
    timeout: 8
    away_timeout: 40
```

to:

```
  - platform: mqtt_room
    device_id: "iBeacon:e59ed151-4d13-4328-b777-f92449088eb0_100_1"
    name: 'Mi watch BLE'
    state_topic: 'espresense/devices/iBeacon:e59ed151-4d13-4328-b777-f92449088eb0_100_1'
    timeout: 8
    away_timeout: 40
```
Enabling send to rooms and switching back isn`t working at all

Please help me

**Comment by N3rdix** [comment]
Config looks good to me, I assume you restarted HA to apply the changes?
Have you checked the topic is correct and states are received (e.g. with MQTT explorer or by listening to the topic in the mqtt integration temporarily)?

**Comment by jar87** [comment]
> Config looks good to me, I assume you restarted HA to apply the changes? Have you checked the topic is correct and states are received (e.g. with MQTT explorer or by listening to the topic in the mqtt integration temporarily)?

Heyt. Thank You for fast reply. HA is fully restarting every time when i`m updating something with espresense.  All Espresense boards are discovered byu MQTT and i can see all their details in Home Assistant. Issue is only with created sensor "Mi Watch BLE". All time it`s having not_home status...

**Comment by rwjack** [comment]
Do you see the device in the fingerprints menu?

http://espresense_ip/ui/#/fingerprints

**Comment by jar87** [comment]
> Do you see the device in the fingerprints menu?
> 
> http://espresense_ip/ui/#/fingerprints

Yes i see. 

Only thing which is strange for me (but i`ve also tried all options) is naming in fingerprints my iBeacon like: iBeacon:e59ed151-4d13-4328-b777-f92449088eb0-100-1

and in hope assistant app it`s name is: iBeacon:e59ed151-4d13-4328-b777-f92449088eb0_100_1

But like i wrote above i`ve tested all options, without any result:(

**Comment by rwjack** [comment]
I feel your pain, when I was switching to the devices topic and it broke, it basically broke my entire smart home. (My dumb ass was updating espresense at 11pm right before bed, imagine having to troubleshoot at that point)

Anyways, wish I could help you, though this is a good lesson for us about redundancy and upgrade management.

**Comment by N3rdix** [comment]
> and in hope assistant app it`s name is: iBeacon:e59ed151-4d13-4328-b777-f92449088eb0_100_1

That’s coming from your long device_id I guess, you can literally use any id here and this should not affect the update at all.
I would still recommend to check espresense is really publishing states to exactly this topic. If so you could dig deeper by enabling debug mode in HA for the mqtt_room component (homeassistant.components.mqtt_room)

**Comment by jar87** [comment]
> I feel your pain, when I was switching to the devices topic and it broke, it basically broke my entire smart home. (My dumb ass was updating espresense at 11pm right before bed, imagine having to troubleshoot at that point)
> 
> Anyways, wish I could help you, though this is a good lesson for us about redundancy and upgrade management.

30% od automations and all speakers are now down:/ I`ve tried downgrade espresense to older version but issue is still.. I believe in HA 2023.11 something has been changed but i have no idea what...

**Comment by jar87** [comment]
> > and in hope assistant app it`s name is: iBeacon:e59ed151-4d13-4328-b777-f92449088eb0_100_1
> 
> That’s coming from your long device_id I guess, you can literally use any id here and this should not affect the update at all. I would still recommend to check espresense is really publishing states to exactly this topic. If so you could dig deeper by enabling debug mode in HA for the mqtt_room component (homeassistant.components.mqtt_room)

I found only this this issue (i have 3 espressenses):

`WARNING (MainThread) [homeassistant.components.mqtt.mixins] MQTT entity name starts with the device name in your config {'device': {'identifiers': ['espresense_001575'], 'connections': [['mac', 'C8:F0:9E:75:15:00']], 'name': 'ESPresense Sypialnia_espresense', 'suggested_area': 'Sypialnia_espresense', 'sw_version': 'v3.1.1', 'manufacturer': 'ESPresense (esp32)', 'configuration_url': 'http://192.168.1.234', 'model': 'ESP32-D0WDQ5'}, 'name': 'ESPresense Sypialnia_espresense Count', 'unique_id': 'espresense_001575_count', 'availability_topic': 'espresense/rooms/sypialnia_espresense/status', 'state_topic': 'espresense/rooms/sypialnia_espresense/telemetry', 'value_template': Template<template=({{ value_json.count }}) renders=0>, 'force_update': False, 'enabled_by_default': True, 'payload_available': 'online', 'qos': 0, 'availability_mode': 'latest', 'encoding': 'utf-8', 'payload_not_available': 'offline'}, this is not expected. Please correct your configuration. The device name prefix will be stripped off the entity name and becomes 'Count'`

The big problem is: i have no idea where i can change name... In all cases from beginning i`m naming devices by first name of room, then sensor. In that sace "sypialnia_espresense (bedroom_espresense). And it`s telling me thaat somewhere is name esporesense sypialnia_espresense. I have no idea where search it:/

**Comment by N3rdix** [comment]
I don’t think this warning is related, but recently the unique_id parameter was added to mqtt_room. Set it to a name which reflects the advice in the mqtt warning and then you can also change the entity_id later in the HA dashboard:
image

coming back to your initial request, without some debug logs i fear it will be hard to help.
Maybe starting from scratch makes a difference, remove your mqtt_room entries, restart, add them again and restart once more. Doesn’t sound logical, but sometimes exactly the weird steps help

**Comment by jar87** [comment]
> ng and then you can also change the entity_id later in the HA dashboard

When i`m clicking on "settings" at my phone sensor (it`s called watch because in past i used watch, and i didn`t updated sensor names at all) it`s telling me that sensor.mi_watch_ble din`t have unique id...

I`ve reflashed espresense board, but it didn`t worked:(

**Comment by N3rdix** [comment]
You first need to add unique_id to the config, then you can enter the settings and change the entity id if Still needed.

there is no (known) issue in espresense or mqtt_room, so its not a general problem. My setup still works on both newest versions

**Comment by jar87** [comment]
Maybe my question is stupid (i`m sure it is) but where in config (which config) should i add uniqie_id? I`m sorry for that kind of stupid questions..:/

**Comment by N3rdix** [comment]
In your mqtt_room sensors, see https://www.home-assistant.io/integrations/mqtt_room/#unique_id

**Comment by jar87** [comment]
Thank You. I will check everything tomorrow and let You know!:)

**Comment by DTTerastar** [comment]
_100_1 is not an id you got from espresense, all my ids are kebab case, not slug.  Copy and paste from mqtt explorer.

**Comment by jar87** [comment]
This is exactly what i`m receiving from esp fingerprint:

iBeacon:e59ed151-4d13-4328-b777-f92449088eb0-100-1

-100-1 isn`t working with configuration.yaml, i don`t know why.  _100_1 is working

**Comment by N3rdix** [comment]
> This is exactly what i`m receiving from esp fingerprint:
> 
> iBeacon:e59ed151-4d13-4328-b777-f92449088eb0-100-1
> 
> -100-1 isn`t working with configuration.yaml, i don`t know why. _100_1 is working

Then it’s clear why it’s not working, topic must exactly the reported one. Have you tried removing the ' around the topic? Or what’s not working, do you get an error?

**Comment by jar87** [comment]
I've changed name to exactly with - 100-1 but it's not working. What you mean by tried removing the around topic?

**Pull request merged**
