### PR TITLE
I2C BME280 & TSL2561 support + two I2C buses

### PR DESCRIPTION
**Pull request by ShonP40**
Adds support for the I2C version of the BME280 and TSL2561 sensors as well as support for two I2C buses.

image

image

More info: 
- BME280: https://www.bosch-sensortec.com/products/environmental-sensors/humidity-sensors-bme280/
- TSL2561: https://ams.com/en/tsl2561

### CODE REVIEW

**Comment by corgan2222** [comment]
Nice!

**Comment by DTTerastar** [comment]
I feel like trying to support all the worlds sensors could compromise the main mission of ESPresense.  Maybe we can these all optional kinda like how tasmota has a full and a minimal?

**Comment by ShonP40** [comment]
I can add a condition for it (if you want) to compile a core binary or core+sensors (full) binary

**Comment by ShonP40** [comment]
> I feel like trying to support all the worlds sensors could compromise the main mission of ESPresense. Maybe we can these all optional kinda like how tasmota has a full and a minimal?

Maybe it'll be better to merge this PR first and then I'll start implementing that system in a separate PR?

**Comment by DTTerastar** [comment]
Ok the sensors builds are ready.  Just make sure all your code is in the #ifdef SENSORS

**Comment by ShonP40** [comment]
Alright, added it and merged your commits

**Review by DTTerastar — APPROVED** [review]

**Pull request merged**
