### PR TITLE
slugified and informative enrollments

### PR DESCRIPTION
**Pull request by AlfredJKwack**
As per discussion on issue #675 this is a quick implementation of the slugified enrollment ID. 

Features: 
- slugifies the user's input prior to sending over the socket
- upon clicking enroll:
  - some useful indications are displayed.
  - The slugified text is rendered for the user.

### CODE REVIEW

**Comment by AlfredJKwack** [comment]
Screenshot of what happens when you click Enroll. 

Screen Shot 2022-09-17 at 17 28 27

**Comment by DTTerastar** [comment]
Why did you close this?  It looks good other than the deleting the vite config.

**Comment by AlfredJKwack** [comment]
Oopsie. Was doing some winter cleaning.

**Comment by DTTerastar** [comment]
I decided to do the slugify on the microcontroller, reworking this w/ the nicer status

**Pull request closed without merging**
