### PR TITLE
mDNS advertisement 

### PR DESCRIPTION
**Pull request by Matsuo3rd**
Current configuration for GL-S10 v2.1 ethernet clk is wrong conducting to inconsistent connectivity.
See https://community.home-assistant.io/t/gl-s10-v2-1-packet-loss-issues/486575
Tested on my device: 0% packet loss!

### CODE REVIEW

**Comment by Matsuo3rd** [comment]
I screwed up. This PR actually contains 2 changes: both GL-S10 Ethernet fix and mDNS advertisement. Please indicate if you want me to start over.

**Comment by DTTerastar** [comment]
> I screwed up. This PR actually contains 2 changes: both GL-S10 Ethernet fix and mDNS advertisement. Please indicate if you want me to start over.

I put the clock fix in master.  For mDNS we already have some code that turns it on, but it's currently tied to the ota updates.  We could make those options separate.  This has some seperate code that does something similar and the 2 may conflict.  Right?

**Comment by Matsuo3rd** [comment]
> I put the clock fix in master.

Thanks for your kindness with my messy PR.

> We could make those options separate. This has some seperate code that does something similar and the 2 may conflict. 

Sure. I actually don't get what the ArduinoOTA.setMdnsEnabled does. But given the name (OTA) it is sounds related to code upgrade workflow (get latest version). My code makes mDNS available during runtime = whole time ESPresense is running (which is super convenient when managing multiple devices).

**Comment by Matsuo3rd** [comment]
Up

**Pull request closed without merging**
