### PR TITLE
Fix BH1750

### PR DESCRIPTION
**Pull request by manfred-mp**
Hi, first of all big thanks to this project! iPhone 12 tracking has been rock solid. 

However BH1750 lux sensor didn't work at all after first measurement. After that nothing. This will fix readings and also prevent flooding mqtt api with sensor delay like other sensors have. 

BME280 works ok.

ESP32 with v3.0.4

Cheers,
-m

### CODE REVIEW

**Comment by DTTerastar** [comment]
Thank you for fixing it!

**Comment by webhostsg** [comment]
Does the fix mean BH1750 does not show real-time lux? Previously when i turn on my lights the value goes up near instant, now it doesn't, breaking some of my automation.

**Comment by manfred-mp** [comment]
Before this fix sensor was saturated and did not work at all for me. This fix is about having same delay as other sensors are having (60s), including TSL2561 light sensor. And like title of this sensor says it is meant for measuring ambient light; cloudy day, day & night etc. Same approach is used in other projects (ESPHome) and commercial products.

**Comment by webhostsg** [comment]
It actually worked fine for me before the 60s delay was introduced. Where I live the ambient light can change pretty quick, due to the clouds. With the fix, lights don't turn on immediately when someone enters a room and it's dark. In ESPHome there is an option to set the update interval for BH1750. My previous Aqara PIR sensor had an ambient light sensor, it is not real-time, and only reports when motion is triggered. I went with ESP and BH1750 for real-time reporting to trigger light switches

**Pull request merged**
