### PR TITLE
Add Feature: simple Blacklist/Whitelist

### PR DESCRIPTION
**Pull request by corgan2222**
### Why: 
with only 3 ESPresense looking for 4 Devices, the MQTT Messages increase extreme to nearly double the amount. 
In highly-frequented areas, there are tons of devices I don't need to track. This also slows down the MQTT Server.

### How:
This is a simple MQTT Filter, not a Bluetooth fingerprint filter. It blocks the MQTT Message if a device-id is found in the filter.
The Log output is untouched.

### Whitelist: 
add the Device-IDs you want to track into the settings field. All MQTT Messages of devices which are not in the list are interrupted.

### Blacklist: 
add the Device-IDs you want to hide into the settings field. All MQTT Messages of these devices are blocked.

Like:
`apple:iphone10-6 apple:iphone13-2`

grafik

### To-Do:
Enhance the filter, to filter earlier on BLE fingerprints. https://github.com/ESPresense/ESPresense/issues/58#issuecomment-941219387
But I don't want to touch this component. 

### Before and After:
grafik

grafik

### CODE REVIEW

**Comment by bluesheep** [comment]
This is a great PR. I'm a heavy home assistant user. If a whitelist is used, could the whitelisted devices publish to MQTT in the format that allows auto discovery?

**Comment by corgan2222** [comment]
> This is a great PR. I'm a heavy home assistant user. If a whitelist is used, could the whitelisted devices publish to MQTT in the format that allows auto discovery?

Do you mean the creation of the mqtt_room sensors for the devices? Hmm I didn't check the mqtt-autodiscover docs, but in theory this could be possible.
I didn't thought about this, but this sounds like a great idea, if I don't overlook something.

**Comment by bluesheep** [comment]
Room Assistant does this for devices listed in its config. (I'm testing both) . I've pasted below MQTT autodiscover message that is posted for my phone. 
```
availability_mode: all
name: 681F6472-A872-4332-9CA6-5A88D0889E0E Room Presence
device:
  identifiers: 681F6472-A872-4332-9CA6-5A88D0889E0E
  name: 681F6472-A872-4332-9CA6-5A88D0889E0E
  via_device: room-assistant-distributed
unique_id: room-assistant-ble-681f6472-a872-4332-9ca6-5a88d0889e0e
state_topic: room-assistant/sensor/ble-681f6472-a872-4332-9ca6-5a88d0889e0e/state
json_attributes_topic: room-assistant/sensor/ble-681f6472-a872-4332-9ca6-5a88d0889e0e/attributes
icon: mdi:bluetooth
availability:
  - topic: room-assistant/sensor/ble-681f6472-a872-4332-9ca6-5a88d0889e0e/status
    payload_available: online
    payload_not_available: offline
  - topic: room-assistant/status/study
    payload_available: online
    payload_not_available: offline
platform: mqtt
```

**Comment by corgan2222** [comment]
Thanks for the Info. First this PR has to be accepted, then we're looking for the next steps. But I have this in mind.

**Comment by maxi1134** [comment]
Any news on this front?

I receive about 100k messages in less than 30 minutes and would like to reduce the slowdowns of my mosquitto server!

I am available for testing dev branches on 7 ESP32s!

**Comment by jonbloom** [comment]
This is awesome! Would love to see this merged in.

@DTTerastar any chance  this could get a review? I'm in a similar situation, 5 nodes tracking 1 beacon generates tons of noise from the other BLE devices around the house. 

@corgan2222 I'd love to see this PR updated to use more inclusive terms, replacing "Whitelist" with "Allow list" or "Include list" and "Blacklist" with "Blocklist" or "Exclude list".

**Comment by DTTerastar** [comment]
> This is awesome! Would love to see this merged in.
> 
> @DTTerastar any chance this could get a review? I'm in a similar situation, 5 nodes tracking 1 beacon generates tons of noise from the other BLE devices around the house.
> 
> @corgan2222 I'd love to see this PR updated to use more inclusive terms, replacing "Whitelist" with "Allow list" or "Include list" and "Blacklist" with "Blocklist" or "Exclude list".

I'm working on this atm.  Right now it uses a lot of cpu to continuously string match.  I'm making it only match when the ids are found/changed.

**Pull request closed without merging**
