### PR TITLE
Switches buttons

### PR DESCRIPTION
**Pull request by creuzerm**
Added Switches and Buttons. 2 of each so we have options. Followed the pattern set forth in the Motion sensor (also why there are two)

Being able to install these ESP32s at useful places like light switches and door switches will increase functionality of ESPresense as we won't need an additional ESPHome device sited next to our ESPresense device to handle this use case.

I will update the https://espresense.com/sensors github source if/when this pull is accepted.

### CODE REVIEW

**Comment by creuzerm** [comment]
Feedback and Suggestions welcome.

**Comment by niceboygithub** [comment]
nice job!

**Comment by hldh214** [comment]
Sorry for reviving this old thread, but have you updated the sensor page as you described? Where can we find the documentation for these switches and buttons? Thanks.

**Comment by creuzerm** [comment]
> Sorry for reviving this old thread, but have you updated the sensor page as you described? Where can we find the documentation for these switches and buttons? Thanks.

It's been a while, but I thought I'd put in instructions into the main docs, maybe it got pruned in a more recent edit.

You pick your pin for the switch and optionally your pullup/pulldown. This way you can use either normally open and normally closed switches and they will react well. If you have the switch wired from the 3 or 5 volt source on the microcontroller, you would pick the pulldown so when it disconnects that 5v doesn't stay/float and look like the switch/button is still closed.

The switches and Buttons are all the same code, they just report to HA slightly differently. You can treat them either way in HA so you can use it all like switches or all like buttons if you want by adjusting how things act in HA.

I like the buttons and a 'toggle' automation myself. A few Normally open buttons wired to the same pin.

**Pull request merged**
