### PR TITLE
Increase internal time

### PR DESCRIPTION
**Pull request by arne182**
Every second is a bit overkill causing home assistant to struggle to visualise the data. Every 5 seconds should be better.

### CODE REVIEW

**Review by DTTerastar — CHANGES_REQUESTED** [review]
There was a request to do the opposite.  So I think we need configuration.

**Comment by arne182** [comment]
I agree. An option to specify how many times the reading is done would be useful.

**Comment by arne182** [comment]
@DTTerastar could you at least make a beta release with one reading every minute until you have the time to make it into a parameter?

**Comment by FvanEgmond** [comment]
Good day, I do agree with @arne182 that 60 seconds is at least a better default interval -at least for now until a user-customizable interval is programmed maybe later- as CO2 and TVOC levels do not change radically within minutes. I therefore sincerely hope that this pull request will be approved soon. 
@DTTerastar, can you set expectations what the chances are that this can be pulled into a new release, and when that is (loosely) planned? :-)    Thanks in advance for your reaction. Cheers, Frank

**Review by DTTerastar — APPROVED** [review]

**Comment by arne182** [comment]
Thanks.

**Comment by AKHwyJunkie** [comment]
I was looking into this as well.  You might be interested to know that the SGP30 (and 40/41) were designed to operate at 1Hz, or once every second.  So, a change would actually go against the chip manufacturer's recommended polling value.  I think the ideal resolution for everyone would be to parameterize all sensor reporting time, per sensor.  Then, users could choose if they want to run in spec or out of spec.  This is obviously much larger in scope, though.

**Comment by arne182** [comment]
I  don't mind the data to be polled every second but the Mqtt reported is a problem for gone assistant to handle. Especially multiple sensors. It would in ideal  to have it poll every second and report if a certain percentage change is reached or the minimum report time is reached. Allowing for the reporting interval to be variable.

**Comment by FvanEgmond** [comment]
Thank you @AKHwyJunkie for this insights. I have the feeling indeed, testing the latest beta with pulling interval of 60 seconds, that the values reported are indeed behaving slightly different than when the pulling interval was 1 second. 
I do agree with @arne182 that the best solution is to split the loop in two: pull every second (with SensorInterval = 1) and report every 60 seconds (with a new variable ReportInterval). 
In later releases, this can be extended to have a flexible report interval, and taking the max or average value of all the values pulled in the seconds in between. How does that sound? :-)

**Pull request merged**
