### PR TITLE
Set wifi via mqtt

### PR DESCRIPTION
**Pull request by DTTerastar**

### CODE REVIEW

**Comment by ozett** [comment]
is it possible now? where is the documentation?
possible to change wifi on console? what commands?

**Comment by ozett** [comment]
dont need the console, it could also be done with usb-connection
image

but still some mqtt examples for config/set would be helpful..

**Comment by RyanWor** [comment]
> dont need the console, it could also be done with usb-connection image
> 
> but still some mqtt examples for config/set would be helpful..

Curious if you or anyone else figured out an example MQTT pub to change the Wi-Fi? 

If possible, it certainly would be much easier than taking a laptop and USB cable around the whole house to each base station. 

I saw several examples for other settings here: https://espresense.com/configuration/mqtt

But Wi-Fi is not a part of that information, and poking around MQTT Explorer I am not seeing any topics that might be for changing SSID/PSK either.

**Comment by DTTerastar** [comment]
https://github.com/ESPresense/ESPresense/blob/f84b89555c0adef43bdd1346e872a65442edc1ec/src/main.cpp#L327

Those are the commands: `wifi-ssid` and `wifi-password`.  

You could change all wifi-ssid at once with:

`espresense/rooms/*/wifi-ssid/set` and `espresense/rooms/*/wifi-password/set` 

reboot afterwords for it to take effect:

`espresense/rooms/*/reboot/set`  **make sure NOT to retain that message or else a reboot loop will occur until you delete it**

**Comment by RyanWor** [comment]
> https://github.com/ESPresense/ESPresense/blob/f84b89555c0adef43bdd1346e872a65442edc1ec/src/main.cpp#L327
> 
> Those are the commands: `wifi-ssid` and `wifi-password`.
> 
> You could change all wifi-ssid at once with:
> 
> `espresense/rooms/*/wifi-ssid/set` and `espresense/rooms/*/wifi-password/set`
> 
> reboot afterwords for it to take effect:
> 
> `espresense/rooms/*/reboot/set` **make sure NOT to retain that message or else a reboot loop will occur until you delete it**

That worked! Thank you so much!

**Comment by DTTerastar** [comment]
Help update some docs so future you won't have to ask! [Edit this page on GitHub](https://github.com/ESPresense/ESPresense.github.io/edit/master/configuration/mqtt.md)

**Pull request merged**
