### PR TITLE
Support for hx711 load sensors

### PR DESCRIPTION
**Pull request by DTTerastar**
Fixes #103 and #429

### CODE REVIEW

**Comment by DTTerastar** [comment]
Works for me: 
image
I used an old bottomless scale that I don't use anymore.  The scale has a esp32 that is SCK GPIO26 and DOUT GPIO27.

**Comment by erwinSmith757** [comment]
i would love some more info on this a little info on which pin, is there extra code involve .... due i want to do the same, and dont want to add another esp to the roam when i can use one

**Comment by DTTerastar** [comment]
The 2 pins are configurable.  Make sure to use -sensors version.

**Comment by Pronown** [comment]
Hello! Thank you for this wonderful code! Curious... How do I calibrate the scale? I am extremely new to HX711's so I may just be misunderstanding what I am reading, but Raw Weight is over 170k. Am I supposed to convert this in some weigh? (Couldn't pass up the pun)

**Comment by DTTerastar** [comment]
You need to do a linear fit w/ the data.  Take 2 weight of a known value, one at the high end and one at the low end.  Then you can calculate the formula to go from raw to kg.

**Comment by Pronown** [comment]
Oh, okay, that makes sense, thank you!

**Comment by nonitex** [comment]
There's actually an integration to do this in HA called "compensation"
```
compensation:
  compensated_weight_kg:
    unique_id: compensated_weight_kg
    source: sensor.espresense_pc_raw_weight_filtered
    data_points:
      - [96000, 0]
      - [1726212, 77.6]
    unit_of_measurement: kg
```
The numbers from the sensor has occasional large jumps so I used this rudimentary filter, it shows the previous measured value instead anything above 2000000:
```
sensor:
  - platform: template
    sensors:
      espresense_pc_raw_weight_filtered:
        unique_id: espresense_pc_raw_weight_filtered
        value_template: >
          {% if states('sensor.espresense_lordok_pc_raw_weight') | int(0) > 2000000 %}
            {{ states('sensor.espresense_pc_raw_weight_filtered) }}
          {% else %}
            {{ states('sensor.espresense_pc_raw_weight') | int(0) }}
          {% endif %}
```
The scale is used as an occupancy sensor on a chair, it becomes occupied if it's between 30 and 90 kg
```
binary_sensor:
  - platform: template
    sensors:
      chair_occupancy:
        value_template: >
          {{ states('sensor.compensated_weight_kg') | float(0) > 30 
            and states('sensor.compensated_weight_kg) | float(0) < 90 }}
```
The compensation integration created a different entity id rather than the one I set ("compensated_weight_kg"), had to look it up with the developer tools.

**Pull request merged**
