### PR TITLE
Add ethernet support (#122)

### PR DESCRIPTION
**Pull request by DTTerastar**

### CODE REVIEW

**Comment by bramstroker** [comment]
I just noticed this PR. Very nice! Is this still a WIP or will this be merged soon?

**Comment by DTTerastar** [comment]
I'm trying to make the selection of board a dropdown... That requires adding dropdown abilities to WifiSettings, once that's done i'll merge it.  But you can try the .bin right now if you'd like.  It worked for my Lilygo.

**Comment by bramstroker** [comment]
That's great. Yes I can do some quick testing. What do I have to enter at "Eternet Type"?

**Comment by DTTerastar** [comment]
I added the dropdown now, so it's obvious... Putting it into the prerelease...

**Comment by bramstroker** [comment]
Ok cool. Can do some testing tomorrow. Wil let you know my findings

**Comment by bramstroker** [comment]
Found some time to test already and can confirm it works as a breeze. Selected ESP32-POE for my olimex esp.
Connected succesfully to LAN and MQTT and I'm receiving incoming messages and sensor updates in HA.
Thanks for your efforts into making this a reality!

**Comment by DTTerastar** [comment]
Sweet!

**Comment by bramstroker** [comment]
Unfortunately I have hit some road bump. Left it running for a few hours without any problems and went to installing it in the final destination.
Powered on with POE, but I am unable to connect to the ESP anymore. Cannot ping the device and no messages in MQTT.
Also the access point appeared again and when I access it the option to set the ethernet has disappeared. See this screenshot.

Screenshot 2022-04-09 at 10 52 01

**Comment by bramstroker** [comment]
Could this be because I enabled OTA updates and it installed the latest stable now?

**Comment by bramstroker** [comment]
Nevermind, it was the pre-release version overwritten by the stable. Just installed the pre-release again and disabled automatic updates for now. 
Running fine now!

**Comment by DTTerastar** [comment]
That's odd, if Prerelease is on it shouldn't update to stable until the newest release is a stable release.

**Comment by DTTerastar** [comment]
Did you turn OFF prerelease?  That'll do that.

**Comment by bramstroker** [comment]
> Did you turn OFF prerelease? That'll do that.

Yes I think I coincidently turned that off.

**Pull request merged**
