### PR TITLE
Support for ESP32-Cam

### PR DESCRIPTION
**Pull request by corgan2222**
Basic Support for ESP32-Cam based on Micro-RTSP

supported Cameras
- ESP32-CAM devboard
- AI-Thinker
- ESP-EYE
- TTGO
- T-Camera
- M5Stack

creates a new webserver on port 8080, which shows a camera stream
To get a still image call ip:8080/jpg

I had a lot of trouble with this port, on which I work on for nearly 3 days. 
At first, on 3 of my 5 ESP32-Cam the camera seems to be broken.

I started developing without the xTaskCreatePinnedToCore(scanForDevices) Thread running. This runs great as expected. I got a stable rtsp stream and good still images.
But with the thread a get random crashes. Maybe these are because of the nimble errors.
I wanted to use https://github.com/circuitrocks/ESP32-RTSP these libs.  The code looks much cleaner and work with threads without handling in the loop. But I could not get the Thread creation to work within ESPpresence.
So had to use this https://github.com/geeksville/Micro-RTSP

@DTTerastar Do you have the M5 ESP Cams and can test it with that?

### CODE REVIEW

**Comment by DTTerastar** [comment]
ACK!  I love it, but I think the esp32 might already be very busy with btle code, adding this might not be a good idea.  Not quite the same as looking at a few pins every once in a while.  From what i've been able to tell, video in general seems to be too much for a esp32.

**Comment by corgan2222** [comment]
Agree, if there is something else going on. If the ESP has nothing to do, the rtsp stream in 640x480 runs smooth. Tested with ESP32-Tasmota.

But I don't think that a video stream inside ESPresence would work well.  But with the possibility to take photos, there can be potential. 

ATM I'm frustrated with this for now and move on to the several sensors which arrived. 
BH1750 lux is ready implemented, just fine-tuning. Should come later today.

Just leave the PR open for some time, maybe I come back to this later, if I have learned more about thread handling. 
Or maybe someone else can pick this up. :)

**Comment by DTTerastar** [comment]
I think this might actually be useful once we do the thermal camera.  A JPEG with the thermal camera overlaid on top of the actual camera would be awesome.

**Comment by DTTerastar** [comment]
> I have not looked into it, but the easiest way could be, to overlay the esp-camera with the thermal camera directly in home-assistant.

I think it'd be cooler to do it in the esp and send it via MQTT.  No idea if that's even possible... Or makes sense to do it that way... IOTLINK sends screenshots as mqtt jpgs...

I don't think trying to stream it via rtsp is practical tho.  Just a pic every once in awhile.

**Pull request closed without merging**
