### PR TITLE
fix: rename mqtt entities to conform to new home assistant reqs

### LINKED ISSUE #997: Error from HA Discovery: Device name is equal to entity name in your config
### Describe the bug

From here https://developers.home-assistant.io/blog/2023-057-21-change-naming-mqtt-entities/

Discovered entities with a name that starts with the device name.

This stops working in version 2024.2.0. Please address before upgrading.

### Version

_No response_

### Active scan enabled

_No response_

### Include filter

_No response_

### Exclude filter

_No response_

### Query filter

_No response_

### Firmware flavor

_No response_

### Device (be specific)

_No response_

### Logs

```text
Some MQTT entities have an entity name that starts with the device name. This is not expected. To avoid a duplicate name the device name prefix is stripped of the entity name as a work-a-round. Please inform the maintainer of the software application that supplies the affected entities to fix this issue.

List of affected entities:

button.espresense_lounge_restart
switch.espresense_lounge_auto_update
button.espresense_garage_restart
number.espresense_garage_max_distance
number.espresense_lounge_absorption
button.espresense_garage_update
light.espresense_lounge_led_1
button.espresense_lounge_enroll
sensor.espresense_garage_free_mem
switch.espresense_lounge_prerelease
light.espresense_garage_led_1
sensor.espresense_lounge_uptime
switch.espresense_garage_auto_update
sensor.espresense_garage_uptime
number.espresense_garage_absorption
number.espresense_lounge_max_distance
sensor.espresense_lounge_free_mem
switch.espresense_lounge_arduino_ota
switch.espresense_garage_arduino_ota
button.espresense_garage_enroll
switch.espresense_garage_prerelease
button.espresense_lounge_update
```

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by SamKirsch10**
Attempts to fix #997. I _think_ I got them all, however HA still is showing me the below three. For the life of me I cannot find where those would be set or if it's just bad historical data or something.

* status_led
* active_scan
* ota_update

### CODE REVIEW

**Comment by tbclark3** [comment]
I don't have those 3 entities on any of my 12 espresense devices. Thanks for this PR!

**Comment by SamKirsch10** [comment]
Thoughts @DTTerastar?

**Review by DTTerastar — APPROVED** [review]

**Comment by broyuken** [comment]
@DTTerastar will the new release be a full version or a beta?

**Comment by DTTerastar** [comment]
Yes, I'm working on fixing some memory troubles leading to crashes.  Once that is all worked out i'll release it.

**Pull request merged**
